CREATE TABLE Cards(

	id INT NOT NULL AUTO_INCREMENT,
	user TEXT NOT NULL,

	cardType TEXT NOT NULL,
	cardCVV TINYTEXT NOT NULL,
	cardNumber TINYTEXT NOT NULL,
	cardExp TINYTEXT NOT NULL,

	PRIMARY KEY(id),
	FOREIGN KEY(user) REFERENCES Users

);