CREATE TABLE Users (

	id INT AUTO_INCREMENT,
	pwd TINYTEXT NOT NULL,
	email TINYTEXT NOT NULL UNIQUE,
	emailVerified CHAR NOT NULL,
	name TINYTEXT NOT NULL,
	phone TINYTEXT NOT NULL,
	isAdmin CHAR NOT NULL,
	createdAt DATETIME NOT NULL,
	updatedAt DATETIME,

	PRIMARY KEY(id)

);